swagger: '2.0'

info:
  description: a very fine description
  title: Gametime Hero backend api
  version: 0.0.1

basePath: /

schemes:
  - https

consumes:
  - application/json

produces:
  - application/json

paths:

  /health:
    get:
      summary: returns OK
      responses:
        '200':
          description: health check successful

  /user:
    post:
      summary: 'Creates a new user.'
      operationId: userCreate
      parameters:
      - name: seed
        in: body
        description: 'The user input.'
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
    get:
      summary: 'Returns all users.'
      operationId: usersList
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UsersList'

  /user/{user_id}:
    get:
      summary: 'Returns an existing user by its ID.'
      operationId: userRead
      parameters:
      - name: user_id
        in: path
        description: 'The ID of the user to be read.'
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
    delete:
      summary: 'Delete an existing user by its ID.'
      operationId: userDelete
      parameters:
      - name: user_id
        in: path
        description: 'The ID of the user to be deleted'
        required: true
        type: string
        format: uuid
      responses:
        '204':
          description: OK
    put:
      summary: 'Update an existing user by its ID.'
      operationId: userUpdate
      parameters:
      - name: user_id
        in: path
        description: 'The ID of the user to be updated.'
        required: true
        type: string
        format: uuid
      - name: seed
        in: body
        description: 'The updated user input.'
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'

  /event:
    post:
      summary: 'Creates a new event.'
      operationId: eventCreate
      parameters:
      - name: seed
        in: body
        description: 'The event input.'
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Event'
    get:
      summary: 'Returns all events.'
      operationId: eventsList
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EventsList'

  /event/{event_id}:
    get:
      summary: 'Returns an existing event by its ID.'
      operationId: eventRead
      parameters:
      - name: event_id
        in: path
        description: 'The ID of the event to be read.'
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Event'
    delete:
      summary: 'Delete an existing event by its ID.'
      operationId: eventDelete
      parameters:
      - name: event_id
        in: path
        description: 'The ID of the event to be deleted'
        required: true
        type: string
        format: uuid
      responses:
        '204':
          description: OK
    put:
      summary: 'Update an existing event by its ID.'
      operationId: eventUpdate
      parameters:
      - name: event_id
        in: path
        description: 'The ID of the event to be updated.'
        required: true
        type: string
        format: uuid
      - name: seed
        in: body
        description: 'The updated event input.'
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Event'
            
definitions:
  EventsList:
    description: 'The list of events.'
    type: array
    items:
      $ref: '#/definitions/Event'

  Event:
    description: 'Event data.'
    type: object
    properties:
      id:
        description: 'Event identifier.'
        type: string
      name:
        description: 'The name of the event.'
        type: string
      updated_at:
        description: 'The date and time that the event was last updated.'
        type: string
        format: date-time
      created_at:
        description: 'The date and time that the event was created.'
        type: string
        format: date-time

  UsersList:
    description: 'The list of users.'
    type: array
    items:
      $ref: '#/definitions/User'

  User:
    description: 'User data.'
    type: object
    properties:
      id:
        description: 'User identifier.'
        type: string
      name:
        description: 'The name of the user.'
        type: string
      updated_at:
        description: 'The date and time that the user was last updated.'
        type: string
        format: date-time
      created_at:
        description: 'The date and time that the user was created.'
        type: string
        format: date-time
